### ISSUE TITLE
Lacking information on tournament date.

### ISSUE THREAD

**Issue by ghost** [dckc/pada1#5]
The date on which each bracket is created is stored on a different page than the one the rest of the data is on. This makes it tricky to access.

**Comment by ghost** [comment]
Resolved.

**Comment by dckc** [comment]
Hey... cool! Glad you got this figured out.

But I don't see the code that does it. The normal thing is to close the issue when the code is shared. I think there's away to do them both in one motion; i.e. you put something like "fixes #5" in your commit message... let's see... yup:
- [Closing issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages)
